### PR TITLE
Fix handle failed state, folder state, and prefix separator on over a day

### LINKED ISSUE #15: handle failed downloads
hello,
the extension does not handle correctly failed downloads: when a download fails I see in the sidebar the message "calculating", instead it should be "failed" or something similar.
Also when I restart the download (using the default firefox downloads toolbar icon) the message still says "calculating" and is not updated (workaround: close and reopen the sidebar).
thanks.

### PR DESCRIPTION
**Pull request by josalhor**
Like the title says, this should close #15 and #16 and another inconsistency I've found while checking the code.

This PR doesn't include a version bump.

I would also like to discuss if the code on getFolderClass that is commented should be removed, it feels weird leaving the code without it and an explanation.

### CODE REVIEW

File: sidebar/panel.js [hunk 1]
```diff
@@ -531,11 +531,21 @@ function start() {
     },
 
     getFolderClass(state) {
+      return "folderEnabled";
+      /*
```
Comment (aesqe) [inline sidebar/panel.js]: No need for the comment, better if you just delete it.

I honestly can't remember why the folder icon has a different look based on download state 😕😄

**Review by aesqe — APPROVED** [review]

File: sidebar/panel.js (hunk 1 above)
Comment (josalhor) [reply sidebar/panel.js]: Done with the next commit. I would still leave a comment there, specially since we are not using the state parameter anymore.

**Review by aesqe — APPROVED** [review]

**Comment by josalhor** [comment]
So, we merge?
